### PR TITLE
Add 'Release' Type for Process nodes

### PR DESCRIPTION
**Pull request by cashweaver-zz**

### CODE REVIEW

**Review by vlayanto-at-dev — COMMENTED** [review]
Line 2548 has debugger keyword. Is it intentional?

**Comment by cashweaver-zz** [comment]
It absolutely wasn't. Thank you for catching that!

**Review by vlayanto-at-dev — APPROVED** [review]

**Comment by vlayanto-at-dev** [comment]
Once you have removed the debugger, I'll approve the changes.

**Comment by cashweaver-zz** [comment]
I've removed the debugger statement.

**Pull request merged**
